### ISSUE TITLE
MakeFile: nmake support

### ISSUE THREAD

**Issue by michidk** [mono/VulkanSharp#30]
Please add support for nmake.
Apparently the "wildcard" parameter does not exist in nmake.

**Comment by wapwork** [comment]
+1 
You delivered a .sln but we cannot make from Visual Studio.

And in the meantime if you could specify what make version to use on Windows it would be helpful. Tried some make/cmake versions for Windows but nothing worked !

**Comment by Jimmacle** [comment]
If you can use Visual Studio you can use that to build VulkanSharp. All you need to do is put the latest vk.xml spec document in the output folder then build the projects through VS.

**Comment by wapwork** [comment]
Thank you Jimmacle, that worked !

**Comment by radekdoulik** [comment]
I made it easier to build on Windows. VS should now download the vk.xml before generating the source.
https://github.com/mono/VulkanSharp/commit/f9f44258740f41db30344c14c097de0a39022594

**Comment by radekdoulik** [comment]
@michidk do you still need to use the nmake now when the solution/csproj downloads the dependencies (vk.xml)? If not, I will close this issue.

Alternatively we can rename the Makefile to GNUmakefile and create simple Makefile compatible with nmake. Or just have Makefile.nmake so that we don't run into issues when GNU makefile is not available on *nix systems.

**Comment by radekdoulik** [comment]
No response, so closing the issue. Feel free to reopen if nmake support is still desired.
